export enum EmailTypeEnum {
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  OLD_VISIT = "OLD_VISIT",
  WELCOME = "WELCOME",
  LOGOUT = "LOGOUT",
  ACCOUNT_RESTORE = "ACCOUNT_RESTORE",
  VERIFY_EMAIL_ON_RESEND = "VERIFY_EMAIL_ON_RESEND",
}
